services:

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - magento_data:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d   # ✅ FIXED
    depends_on:
      - php

  php:
    build: ./docker/php
    volumes:
      - magento_data:/var/www/html
    depends_on:
      - db
      - redis
      - opensearch

  db:
    image: mysql:8
    command: --innodb-buffer-pool-size=512M
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
    ports:
      - "3307:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9201:9200"

volumes:
  magento_data:
