pipeline {
    agent any

    options {
        timeout(time: 40, unit: 'MINUTES')
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Abhiabhi1019/magento-project-local.git'
            }
        }

        stage('Clean Old Containers') {
            steps {
                sh '''
                echo "Cleaning old containers..."
                docker compose down -v || true
                docker system prune -f || true
                '''
            }
        }

        stage('Build & Start Containers') {
            steps {
                sh '''
                docker compose build
                docker compose up -d
                docker compose ps
                '''
            }
        }

        stage('Wait for DB') {
            steps {
                sh '''
                until docker compose exec -T db mysqladmin ping -h "localhost" --silent; do
                    sleep 5
                done
                '''
            }
        }

        stage('Wait for OpenSearch') {
            steps {
                sh '''
                until docker compose exec -T php curl -s http://opensearch:9200 > /dev/null; do
                    sleep 5
                done
                '''
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                docker compose exec -T php bash -c "
                cd /var/www/html &&
                composer install
                "
                '''
            }
        }

        stage('Magento Install') {
            steps {
                sh '''
                docker compose exec -T php bash -c "
                cd /var/www/html &&

                if [ ! -f app/etc/env.php ]; then
                    php -d memory_limit=2G bin/magento setup:install \
                    --base-url=http://localhost:8080 \
                    --db-host=db \
                    --db-name=magento \
                    --db-user=root \
                    --db-password=root \
                    --admin-firstname=admin \
                    --admin-lastname=admin \
                    --admin-email=admin@example.com \
                    --admin-user=admin \
                    --admin-password=Admin123@ \
                    --language=en_US \
                    --currency=USD \
                    --timezone=Asia/Kolkata \
                    --use-rewrites=1 \
                    --search-engine=opensearch \
                    --opensearch-host=opensearch \
                    --opensearch-port=9200
                fi
                "
                '''
            }
        }

        stage('Deploy Magento') {
            steps {
                sh '''
                docker compose exec -T php bash -c "
                cd /var/www/html &&
                php -d memory_limit=2G bin/magento setup:upgrade &&
                php -d memory_limit=2G bin/magento cache:flush
                "
                '''
            }
        }

        stage('Verify') {
            steps {
                sh 'docker ps'
            }
        }
    }
}
