pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Abhiabhi1019/magento-project-local.git'
            }
        }

        stage('Debug Paths') {
            steps {
                sh '''
                echo "===== DEBUG START ====="
                pwd
                ls -la
                echo "Check nginx config:"
                ls docker/nginx/
                echo "Check docker-compose:"
                ls docker-compose.yml
                echo "===== DEBUG END ====="
                '''
            }
        }

        stage('Check Docker') {
            steps {
                sh '''
                docker --version || echo "Docker not installed"
                docker compose version || echo "Docker Compose not installed"
                '''
            }
        }

        stage('Deploy Containers') {
            steps {
                sh '''
                echo "Stopping old containers..."
                docker compose down || true

                echo "Building containers..."
                docker compose build

                echo "Starting containers..."
                docker compose up -d
                '''
            }
        }

        stage('Verify Containers') {
            steps {
                sh '''
                echo "Running containers:"
                docker ps
                '''
            }
        }
    }
}
